node {

    stage('Initialize'){
 
    }

    stage('Checkout') {
		checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/crismarfr/microservices.git']]])
    }
}
